name: PHP Composer

on:
  push:

  pull_request:
    types: [assigned, opened, synchronize, reopened]

  schedule:
    - cron: '34 3 * * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install XeTeX
        run: sudo apt-get install texlive-xetex

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Install Composer and Dependencies
        run: curl -s http://getcomposer.org/installer | php && php composer.phar self-update && php composer.phar install

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Prepare Database
        run: export MYSQL_PWD=root && mysql --default-character-set=utf8 -h 'localhost' -P '3306' -u 'root' -v -e "CREATE DATABASE IF NOT EXISTS opusdb DEFAULT CHARACTER SET = UTF8 DEFAULT COLLATE = UTF8_GENERAL_CI; CREATE USER IF NOT EXISTS 'opus4admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'; GRANT ALL PRIVILEGES ON opusdb.* TO 'opus4admin'@'localhost'; CREATE USER IF NOT EXISTS 'opus4'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'; GRANT SELECT,INSERT,UPDATE,DELETE ON opusdb.* TO 'opus4'@'localhost'; FLUSH PRIVILEGES;"

      - name: Prepare Test Environment
        run: |
          ant prepare-workspace prepare-config -DdbUserPassword=root -DdbAdminPassword=root
          php test/TestAsset/createdb.php

      - name: Install Fonts
        run: |
          mkdir -p /usr/share/fonts/opentype
          wget https://fonts.google.com/download?family=Open%20Sans -O Open_Sans.zip
          sudo apt-get install unzip
          unzip -o Open_Sans.zip -d Open_Sans
          cp -r Open_Sans/static/OpenSans/ /usr/share/fonts/opentype/
          sudo apt-get install fontconfig
          fc-cache -f -v

      - name: Tests
        run: php composer.phar test

      - name: Coding Style
        run: php composer.phar cs-check
